### ISSUE TITLE
'Namespace' object has no attribute 'validation'

### ISSUE THREAD

**Issue by 106084** [akku1506/Feature-Generating-Networks-for-ZSL#2]
I encountered the following problem when I ran your code.
Traceback (most recent call last):
  File "classifier.py", line 210, in <module>
    data = util.DATA_LOADER(opt)
  File "/home/suxiangdong/inpainting/gan/zsl/util.py", line 18, in __init__
    self.read_matdataset(opt)
  File "/home/suxiangdong/inpainting/gan/zsl/util.py", line 42, in read_matdataset
    if not opt.validation:
AttributeError: 'Namespace' object has no attribute 'validation'

**Comment by akku1506** [comment]
Hi @106084 ,

This happens because there was no option regarding validation set in classifier.py. Add the below piece of code at line 180 of classifier.py. It should solve your problem.
 
parser.add_argument('--validation', action='store_true', default=False, help='enable cross validation mode')

Thank You.

**Comment by 106084** [comment]
@akku1506 
My problem is solved, thank you.
